export const BASE = 'BASE'

export const UX_TYPES = {
  UI: 'UI',
  SESSION: {
    SIGN_UP: 'SIGN_UP',
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT'
  },
  ERRORS: {
    AUTH: {
      INVALID_PASSWORD: 'INVALID PASSWORD',
      INVALID_EMAIL: 'INVALID EMAIL',
      BOTH: 'INVALID CREDENTIALS',
      INVALID_CREDENTIALS: 'INVALID CREDENTIALS',
      SOMETHING_WRONG: 'SOMETHING WRONG',
      CLEAR_ERRORS: 'CLEAR ERRORS',
      USER_DOES_NOT_EXIST: 'USER DOES NOT EXIST'
    }
  }
}

export const USERS_TYPES = {
  USER: 'USER'
}

export const COURSES_TYPES = {
  COURSE: 'COURSE'
}

export const RACES_TYPES = {
  RACE: 'RACE'
}

export const PATHS_TYPES = {
  PATH: 'PATH'
}

export const WAYPOINTS_TYPES = {
  WAYPOINT: 'WAYPOINT'
}